
FROM thehiveproject/cortex:latest

USER root
RUN apt update && apt upgrade -y
RUN apt install -y \
 python3-pip python3-dev 

#RUN rm -rf /var/lib/apt/lists/* 

RUN pip3 install -U pip setuptools
RUN pip3 install cortexutils
RUN pip3 install ldap3 requests






#RUN for I in analyzers/*/requirements.txt; do pip3 install -U -r $I || true; done



#FROM thehiveproject/cortex:latest
#
#RUN apt-get update && apt-get upgrade -y
#RUN apt-get install -y --no-install-recommends                        \
#        python3-pip python2.7-dev python3-pip python3-dev              \
#        ssdeep libfuzzy-dev libfuzzy2 libimage-exiftool-perl          \
#        libmagic1 build-essential git libssl-dev dnsutils iptables
#
#RUN pip3 install -U pip setuptools
#RUN pip3 install cortexutils
#RUN git clone https://github.com/TheHive-Project/Cortex-Analyzers.git \
#        /opt/Cortex-Analyzers
#
#RUN chown -R cortex:cortex /opt/
#RUN chown -R cortex:cortex /etc/cortex
#RUN chown -R cortex:cortex /var/log/cortex
#RUN chown -R cortex:cortex /tmp/
#
#
#USER cortex
#
#RUN for I in analyzers/*/requirements.txt; do pip3 install -U -r $I || true; done



