version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      #- xpack.ml.enabled=false
      - discovery.type=single-node
      #- xpack.monitoring.collection.enabled=true
    ports:
      - "${ES_PORT}:${ES_PORT}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - es-data:/usr/share/elasticsearch/data

  #-------------------------------------
  kibana:
    image: kibana:${STACK_VERSION}
    container_name: kibana
    restart: always
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "${KIBANA_PORT}:${KIBANA_PORT}"
    depends_on:
      - elasticsearch
  
  #-------------------------------------
  cassandra:
    container_name: cassandra
    image: cassandra:3.11
    restart: unless-stopped
    hostname: cassandra
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=1G
      - CASSANDRA_CLUSTER_NAME=thp
    volumes:
      - ./cassandra/data:/var/lib/cassandra/data
    #networks:
    #  - backend
  #-------------------------------------  
  cortex:
    image: thehiveproject/cortex:latest
    container_name: cortex
    hostname: cortex
    restart: unless-stopped
    depends_on:
      - elasticsearch
    environment:
      - 'JOB_DIRECTORY=/opt/cortex/jobs'
    ports:
      #- "0.0.0.0:9001:9001"
      - "9001:9001"
    command:
      --job-directory ${JOB_DIRECTORY}
    volumes:
      - ./cortex/application.conf:/etc/cortex/application.conf
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./cortex/log/:/var/log/cortex
      #- /tmp:/tmp
      - ./cortex/Cortex-Analyzers:/opt/cortex/analyzers
      - ./cortex/Cortex-Analyzers/analyzers.json:/opt/cortex/analyzers/analyzers.json
    privileged: true
  
  #-------------------------------------u
  thehive:
    container_name: thehive
    hostname: thehive
    image: 'thehiveproject/thehive4:latest'
    restart: unless-stopped
    depends_on:
      - cassandra
    ports:
      #- '0.0.0.0:9000:9000'
      - '9000:9000'
    volumes:
      - ./thehive/application.conf:/etc/thehive/application.conf
      - ./thehive/data:/opt/thp/thehive/data
      - ./thehive/index:/opt/thp/thehive/index
    command:
      --cortex-port 9001
      --cortex-keys ${CORTEX_KEY}
      #--es-uri http://elasticsearch:9200
      #--no-config 
      #--no-config-secret
     
    #networks:
    #  - proxy
    #  - backend

  #-------------------------------------    
  ubuntu:
    depends_on:
      - elasticsearch
      - kibana
    container_name: ubuntu
    hostname: ubuntu_nginx
    environment:
      - BEATS_STRICT_PERMS=false
    #build:
    #  context: ./ubuntu/
    #  dockerfile: dockerfile
    image: ubuntu-nginx-beats:1.0
    restart: always
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    command: bash -c "./tmp/start.sh"
  
  #-------------------------------------
  ElasticAlert:
    depends_on:
      - elasticsearch
    container_name: ElasticAlert2
    hostname: ElasticAlert2
    image: jertel/elastalert2:latest
    volumes:
    - type: bind
      source: ./elast-alert/config.yaml
      target: /opt/elastalert/config.yaml
    - type: bind
      source: ./elast-alert/rules
      target: /opt/elastalert/rules 
    restart: always

volumes:
  es-data:
    driver: local